In [1]:
%matplotlib inline
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def img_show(model):
    plt.imshow(model)
    plt.xticks([])
    plt.yticks([])
    plt.show()

In [3]:
a = cv.imread('a.jpg')

In [6]:
a.shape

(1251, 1875, 3)

In [7]:
for i in a:
    print(i)

[[110 156 214]
 [110 156 214]
 [109 155 213]
 ...
 [101 152 215]
 [101 152 215]
 [102 153 216]]
[[111 157 215]
 [111 157 215]
 [110 156 214]
 ...
 [ 96 148 214]
 [ 96 148 214]
 [ 96 148 214]]
[[105 151 209]
 [105 151 209]
 [104 150 208]
 ...
 [ 92 145 212]
 [ 92 145 212]
 [ 92 145 212]]
[[112 158 216]
 [112 158 216]
 [111 157 215]
 ...
 [ 87 142 211]
 [ 87 142 211]
 [ 87 142 211]]
[[118 165 221]
 [118 165 221]
 [117 164 220]
 ...
 [ 81 138 207]
 [ 81 138 207]
 [ 80 137 206]]
[[116 163 219]
 [116 163 219]
 [115 162 218]
 ...
 [ 78 135 204]
 [ 78 135 204]
 [ 77 134 203]]
[[112 159 215]
 [113 160 216]
 [113 160 216]
 ...
 [ 83 138 205]
 [ 83 138 205]
 [ 83 138 205]]
[[ 99 146 202]
 [100 147 203]
 [100 147 203]
 ...
 [ 92 145 208]
 [ 92 145 208]
 [ 92 145 208]]
[[103 148 205]
 [103 148 205]
 [103 148 205]
 ...
 [ 94 144 202]
 [ 94 144 202]
 [ 94 144 202]]
[[ 95 140 197]
 [ 95 140 197]
 [ 96 141 198]
 ...
 [121 168 222]
 [121 168 222]
 [121 168 222]]
[[ 96 142 196]
 [ 96 142 196]
 [ 97 143 

 [ 75 104 135]]
[[112 160 212]
 [113 161 213]
 [113 161 213]
 ...
 [ 77 107 132]
 [ 77 107 132]
 [ 77 107 132]]
[[107 155 207]
 [107 155 207]
 [108 156 208]
 ...
 [ 80 104 122]
 [ 84 108 126]
 [ 83 107 125]]
[[106 154 206]
 [106 154 206]
 [107 155 207]
 ...
 [ 64  76  88]
 [ 68  80  92]
 [ 68  80  92]]
[[115 162 213]
 [115 162 213]
 [116 163 214]
 ...
 [ 60  59  68]
 [ 63  62  71]
 [ 63  62  71]]
[[122 170 218]
 [123 171 219]
 [124 172 220]
 ...
 [ 73  62  65]
 [ 75  64  67]
 [ 75  64  67]]
[[127 173 221]
 [127 173 221]
 [128 174 222]
 ...
 [ 76  62  63]
 [ 77  63  64]
 [ 77  63  64]]
[[136 180 227]
 [135 179 226]
 [134 178 225]
 ...
 [ 73  63  63]
 [ 73  63  63]
 [ 73  63  63]]
[[138 182 229]
 [137 181 228]
 [136 180 227]
 ...
 [ 68  67  63]
 [ 68  67  63]
 [ 68  67  63]]
[[131 175 222]
 [131 175 222]
 [131 175 222]
 ...
 [ 62  68  63]
 [ 61  67  62]
 [ 61  67  62]]
[[120 162 207]
 [121 163 208]
 [121 163 208]
 ...
 [ 69  65  64]
 [ 69  65  64]
 [ 69  65  64]]
[[122 167 211]
 [122 167

In [8]:
m = cv.imread('m.jpg')

In [9]:
m.shape

(360, 480, 3)

In [12]:
n = m.flatten()

In [13]:
n.shape

(518400,)

In [16]:
i_list = list()

In [17]:
for i in n:
    i_list.append(i)

In [19]:
print(i_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [20]:
print(m)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
